export const types = {
    ADDCUSTOMER_STARTED: 'ADDCUSTOMER_STARTED',
    ADDCUSTOMER_SUCCESS: 'ADDCUSTOMER_SUCCESS',
    ADDCUSTOMER_FAILURE: 'ADDCUSTOMER_FAILURE',
    SHOWCUSTOMERLIST_STARTED: 'SHOWCUSTOMERLIST_STARTED',
    SHOWCUSTOMERLIST_SUCCESS: 'SHOWCUSTOMERLIST_SUCCESS',
    SHOWCUSTOMERLIST_FAILURE: 'SHOWCUSTOMERLIST_FAILURE',
    DELETECUSTOMER_STARTED: 'DELETECUSTOMER_STARTED',
    DELETECUSTOMER_SUCCESS: 'DELETECUSTOMER_SUCCESS',
    DELETECUSTOMER_FAILURE: 'DELETECUSTOMER_FAILURE',
    UPDATECUSTOMER_STARTED: 'UPDATECUSTOMER_STARTED',
    UPDATECUSTOMER_SUCCESS: 'UPDATECUSTOMER_SUCCESS',
    UPDATECUSTOMER_FAILURE: 'UPDATECUSTOMER_FAILURE',
}